#this file generated by githubTemplates2nix
let tarUrlToDrv = (import /nix/store/b95f2hfg12g5dk22nmnxbq58yl97j0zc-githubTemplate2nix/templatesUtils.nix).tarUrlToDrv;
in
{
    test = tarUrlToDrv { name = "test"; url = "https://github.com/countoren/GithubTemplates2nix/archive/ad6f47d8ad3e2f02b54660baeedceb7c2075cb7c.tar.gz"; };
}
